album_new:
    path: /create
    defaults: { _controller: "AppBundle:Album:create"}
    methods: POST

album_list:
    path: /
    defaults: { _controller: "AppBundle:Album:list"}
    methods: GET

album_get:
    path: /{id}
    defaults: { _controller: "AppBundle:Album:get"}
    methods: GET

album_edit:
    path: /edit
    defaults: { _controller: "AppBundle:Album:edit"}
    methods: PUT

album_delete:
    path: /delete
    defaults: { _controller: "AppBundle:Album:delete"}
    methods: