comment_create:
    path: /create
    defaults: { _controller: "AppBundle:Comment:create"}
    methods: POST

comment_list:
    path: /
    defaults: { _controller: "AppBundle:Comment:list"}
    methods: GET

comment_get:
    path: /{id}
    defaults: { _controller: "AppBundle:Comment:get"}
    methods: GET

comment_edit:
    path: /edit
    defaults: { _controller: "AppBundle:Comment:edit"}
    methods: PUT

comment_delete:
    path: /delete
    defaults: { _controller: "AppBundle:Comment:delete"}
    methods: