user_new:
    path: /create
    defaults: { _controller: "AppBundle:User:create"}
    methods: POST

user_list:
    path: /list
    defaults: { _controller: "AppBundle:Default:index"}
    methods: GET

user_edit:
    path: /edit
    defaults: { _controller: "AppBundle:Default:index"}
    methods: PUT

user_delete:
    path: /delete
    defaults: { _controller: "AppBundle:Default:index"}
    methods: