photo_create:
    path: /create
    defaults: { _controller: "AppBundle:Photo:create"}
    methods: POST

photo_list:
    path: /
    defaults: { _controller: "AppBundle:Photo:list"}
    methods: GET

photo_get:
    path: /{id}
    defaults: { _controller: "AppBundle:Photo:get"}
    methods: GET

photo_edit:
    path: /edit
    defaults: { _controller: "AppBundle:Photo:edit"}
    methods: PUT

photo_delete:
    path: /delete
    defaults: { _controller: "AppBundle:Photo:delete"}
    methods: