user_create:
    path: /create
    defaults: { _controller: "AppBundle:User:create"}
    methods: POST

user_list:
    path: /
    defaults: { _controller: "AppBundle:User:list"}
    methods: GET

user_get:
    path: /{id}
    defaults: { _controller: "AppBundle:User:get"}
    methods: GET

user_edit:
    path: /edit
    defaults: { _controller: "AppBundle:User:edit"}
    methods: PUT

user_delete:
    path: /delete
    defaults: { _controller: "AppBundle:User:delete"}
    methods: